name: Build APK Flet

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          pip install --upgrade pip
          pip install flet

      - name: Gerar APK
        run: |
          flet build apk

      - name: Salvar APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: build/apk/*.apk